name: Bind9 Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  build_wolfprovider:
    uses: ./.github/workflows/build-wolfprovider.yml
    with:
      wolfssl_ref: ${{ matrix.wolfssl_ref }}
      openssl_ref: ${{ matrix.openssl_ref }}
      replace_default: ${{ matrix.replace_default || false }}
    strategy:
      matrix:
        wolfssl_ref: [ 'master', 'v5.8.0-stable' ]
        openssl_ref: [ 'openssl-3.5.0' ]
        replace_default: [ false, true ]

  test_bind:
    runs-on: ubuntu-22.04
    container:
      image: debian:bookworm
      env:
        DEBIAN_FRONTEND: noninteractive
    needs: build_wolfprovider
    # This should be a safe limit for the tests to run.
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        bind_ref: [ 'v9.18.28' ]
        wolfssl_ref: [ 'master', 'v5.8.0-stable' ]
        openssl_ref: [ 'openssl-3.5.0' ]
        replace_default: [ false, true ]
        force_fail: ['WOLFPROV_FORCE_FAIL=1', '']
    steps:
      - name: Install sudo
        run: |
          apt-get update
          apt-get install -y sudo

      - name: Checkout wolfProvider
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Retrieving wolfSSL/wolfProvider from cache
        uses: actions/cache/restore@v4
        id: wolfprov-cache
        with:
          path: |
            wolfssl-install
            wolfprov-install
            openssl-install/lib64
            openssl-install/include
            openssl-install/bin
            ${{ matrix.replace_default && 'libdefault-stub-install' || '' }}

          key: wolfprov${{ matrix.replace_default && '-replace-default' || '' }}-${{ matrix.wolfssl_ref }}-${{ matrix.openssl_ref }}-${{ github.sha }}
          fail-on-cache-miss: true

      - name: Install bind9 test dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt install -y build-essential automake libtool gnutls-bin \
          pkg-config make libidn2-dev libuv1-dev libnghttp2-dev libcap-dev \
          libjemalloc-dev zlib1g-dev libxml2-dev libjson-c-dev libcmocka-dev \
          python3-pytest python3-dnspython python3-hypothesis net-tools iproute2
          sudo PERL_MM_USE_DEFAULT=1 cpan -i Net::DNS

      - name: Checkout bind9
        uses: actions/checkout@v4
        with:
          repository: isc-projects/bind9
          path: bind9
          ref: ${{ matrix.bind_ref }}
          fetch-depth: 1

      - name: Checkout OSP
        uses: actions/checkout@v4
        with:
          repository: wolfssl/osp
          path: osp
          fetch-depth: 1
      - run: |
          cd bind9
          patch -p1 < $GITHUB_WORKSPACE/osp/wolfProvider/bind9/bind9-${{ matrix.bind_ref }}-wolfprov.patch

      - name: Build and test bind9 with wolfProvider
        working-directory: bind9
        shell: bash
        run: |
          # Set up the environment for wolfProvider
          source $GITHUB_WORKSPACE/scripts/env-setup

          autoreconf -ivf
          ./configure
          make clean
          make -j$(nproc)
          sudo ./bin/tests/system/ifconfig.sh up

          export ${{ matrix.force_fail }}
          make -j$(nproc) check 2>&1 | tee bind9-test.log
          TEST_RESULT=${PIPESTATUS[0]}
          $GITHUB_WORKSPACE/.github/scripts/check-workflow-result.sh $TEST_RESULT ${{ matrix.force_fail }} bind9
