name: Build wolfProvider

on:
  workflow_call:
    inputs:
      wolfssl_ref:
        required: true
        type: string
      openssl_ref:
        required: true
        type: string
      replace_default:
        required: false
        type: boolean
        default: false
        description: "Build with --replace-default flag"
    outputs:
      cache_key:
        description: "Cache key for the build artifacts"
        value: ${{ jobs.build_wolfprovider_common.outputs.cache_key }}

jobs:
  build_wolfprovider_common:
    name: Build wolfProvider
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    outputs:
      cache_key: wolfprov${{ inputs.replace_default && '-replace-default' || '' }}-${{ inputs.wolfssl_ref }}-${{ inputs.openssl_ref }}-${{ github.sha }}
    steps:
      - name: Checkout wolfProvider
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get OpenSSL commit hash
        id: openssl-ref
        run: |
          sha=$(./scripts/resolve-ref.sh "${{ inputs.openssl_ref }}" "openssl/openssl")
          echo "ref=$sha" >> "$GITHUB_OUTPUT"
        env:
          # Used token to bypass rate limits
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get WolfSSL commit hash
        id: wolfssl-ref
        run: |
          sha=$(./scripts/resolve-ref.sh "${{ inputs.wolfssl_ref }}" "wolfssl/wolfssl")
          echo "ref=$sha" >> "$GITHUB_OUTPUT"
        env:
          # Used token to bypass rate limits
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Look for a cached version of OpenSSL
      - name: Checking OpenSSL in cache
        uses: actions/cache/restore@v4
        id: openssl-cache
        with:
          path: |
            openssl-install
            ${{ inputs.replace_default && 'libdefault-stub-install' || '' }}
          key: ossl${{ inputs.replace_default && '-replace-default' || '' }}-depends-${{ steps.openssl-ref.outputs.ref }}
          lookup-only: false

      # Look for a cached version of WolfSSL
      - name: Checking WolfSSL in cache
        uses: actions/cache/restore@v4
        id: wolfssl-cache
        with:
          path: |
            wolfssl-install
          key: wolfssl-depends-${{ steps.wolfssl-ref.outputs.ref }}
          lookup-only: false

      - name: Build wolfProvider
        run: |
          # Clean if there's a build mode mismatch
          if ! OPENSSL_TAG=${{ inputs.openssl_ref }} WOLFSSL_TAG=${{ inputs.wolfssl_ref }} ./scripts/build-wolfprovider.sh ${{ inputs.replace_default && '--replace-default' || '' }}; then
            echo "Build failed, attempting distclean and rebuild..."
            ./scripts/build-wolfprovider.sh --distclean
            OPENSSL_TAG=${{ inputs.openssl_ref }} WOLFSSL_TAG=${{ inputs.wolfssl_ref }} ./scripts/build-wolfprovider.sh ${{ inputs.replace_default && '--replace-default' || '' }}
          fi

      # Save the wolfProvider outputs for use by the parent jobs.
      # Note that we don't try to restore since it will likely always 
      # be a cache miss.
      - name: Save wolfProvider into cache
        uses: actions/cache/save@v4
        with: 
          path: |
            wolfssl-install
            wolfprov-install
            openssl-install/lib64
            openssl-install/include
            openssl-install/bin
            ${{ inputs.replace_default && 'libdefault-stub-install' || '' }}
          key: wolfprov${{ inputs.replace_default && '-replace-default' || '' }}-${{ inputs.wolfssl_ref }}-${{ inputs.openssl_ref }}-${{ github.sha }}

      # If openssl cache miss, save it to the cache
      - name: Save OpenSSL into cache
        if: steps.openssl-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with: 
          path: |
            openssl-install
            ${{ inputs.replace_default && 'libdefault-stub-install' || '' }}
          key: ossl${{ inputs.replace_default && '-replace-default' || '' }}-depends-${{ steps.openssl-ref.outputs.ref }}

      - name: Save WolfSSL into cache
        if: steps.wolfssl-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with: 
          path: |
            wolfssl-install
          key: wolfssl-depends-${{ steps.wolfssl-ref.outputs.ref }}

      - name: Print errors
        if: ${{ failure() }}
        run: |
          if [ -f test-suite.log ] ; then
            cat test-suite.log
          fi
