name: Build wolfProvider

on:
  workflow_call:
    inputs:
      wolfssl_ref:
        required: true
        type: string
      openssl_ref:
        required: true
        type: string
    outputs:
      cache_key:
        description: "Cache key for the build artifacts"
        value: ${{ jobs.build_wolfprovider_common.outputs.cache_key }}

jobs:
  build_wolfprovider_common:
    name: Build wolfProvider
    runs-on: ubuntu-22.04
    # Run inside Debian Bookworm to match packaging environment
    container:
      image: debian:bookworm
      env:
        DEBIAN_FRONTEND: noninteractive
    timeout-minutes: 20
    outputs:
      cache_key: wolfprov-${{ inputs.wolfssl_ref }}-${{ inputs.openssl_ref }}-${{ github.sha }}
    steps:
      - name: Set up environment
        run: |
          apt-get update
          apt-get install -y \
            build-essential \
            devscripts \
            debhelper \
            dh-autoreconf \
            libtool \
            pkg-config \
            git \
            wget \
            curl \
            ca-certificates \
            openssl \
            dpkg-dev \
            lintian \
            fakeroot \
            dh-exec \
            equivs \
            expect \
            xxd

      - name: Ensure the working directory safe
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout wolfProvider
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Fetch tags (for Debian versioning)
        run: |
          git fetch --tags --force --prune

      - name: Install wolfSSL Debian packages from repo tarball
        run: |
          mkdir -p "/tmp/wolfssl-pkg"
          chmod +x $GITHUB_WORKSPACE/debian/install-wolfssl.sh
          $GITHUB_WORKSPACE/debian/install-wolfssl.sh \
            $GITHUB_WORKSPACE/.github/packages/debian-wolfssl.tar.gz \
            "/tmp/wolfssl-pkg"

          # Stage wolfSSL debs into artifacts directory
          mkdir -p "/tmp/wolfprov-packages"
          echo "Moving wolfssl files to artifacts directory..."

          find /tmp/wolfssl-pkg -name "*wolfssl*" -type f -name "*.deb" -exec cp {} /tmp/wolfprov-packages/ \;
          find /tmp/wolfssl-pkg -name "*wolfssl*" -type f -name "*.dsc" -exec cp {} /tmp/wolfprov-packages/ \;
          find /tmp/wolfssl-pkg -name "*wolfssl*" -type f -name "*.tar.gz" -exec cp {} /tmp/wolfprov-packages/ \;
          find /tmp/wolfssl-pkg -name "*wolfssl*" -type f -name "*.orig.tar.gz" -exec cp {} /tmp/wolfprov-packages/ \;

      - name: Build Debian packages (wolfProvider + OpenSSL)
        run: |
          yes Y | ./scripts/build-wolfprovider.sh --debian

          echo "Generated packages in parent dir:"
          ls -la ../ || true
          ls -la ../*.deb ../*.dsc ../*.tar.gz 2>/dev/null || true

      - name: Collect package artifacts
        run: |
          mkdir -p "/tmp/wolfprov-packages"
          mv ../*.deb /tmp/wolfprov-packages/ 2>/dev/null || true
          mv ../*.dsc /tmp/wolfprov-packages/ 2>/dev/null || true
          mv ../*.tar.gz /tmp/wolfprov-packages/ 2>/dev/null || true
          echo "Artifacts to upload:"
          ls -la /tmp/wolfprov-packages || true

      - name: Upload wolfSSL packages
        uses: actions/upload-artifact@v4
        with:
          name: wolfssl-debian-packages-${{ github.sha }}
          path: |
            /tmp/wolfprov-packages/*wolfssl*.deb
          retention-days: 7

      - name: Upload OpenSSL/wolfProvider packages
        uses: actions/upload-artifact@v4
        with:
          name: openssl-wolfprov-debian-packages-${{ github.sha }}
          path: |
            /tmp/wolfprov-packages/*openssl*.deb
            /tmp/wolfprov-packages/*libssl3*.deb
            /tmp/wolfprov-packages/*libssl-dev*.deb
            /tmp/wolfprov-packages/*libwolfprov*.deb
          retention-days: 7

      - name: Print errors
        if: ${{ failure() }}
        run: |
          if [ -f test-suite.log ] ; then
            cat test-suite.log
          fi
