name: Build wolfProvider

on:
  workflow_call:
    inputs:
      wolfssl_ref:
        required: true
        type: string
      openssl_ref:
        required: true
        type: string
    outputs:
      cache_key:
        description: "Cache key for the build artifacts"
        value: ${{ jobs.build_wolfprovider_common.outputs.cache_key }}

jobs:
  build_wolfprovider_common:
    name: Build wolfProvider
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    outputs:
      cache_key: wolfprov-${{ inputs.wolfssl_ref }}-${{ inputs.openssl_ref }}-${{ github.sha }}-${{ github.run_number }}
    steps:
      # Check if this version of wolfssl/wolfprovider has already been built,
      # mark to cache these items on post if we do end up building
      # On a push, the first workflow(s) will complete the build and cache it 
      # and any delayed workflow will be able to utilize it.
      # This is not designed to cache builds across commits.
      - name: Checking wolfSSL/wolfProvider in cache
        uses: actions/cache@v4
        id: wolfprov-cache
        with:
          path: |
            .github
            scripts
            wolfssl-install
            wolfprov-install
            openssl-install
            provider.conf
          key: wolfprov-${{ inputs.wolfssl_ref }}-${{ inputs.openssl_ref }}-${{ github.sha }}-${{ github.run_number }}
          lookup-only: true

      # if cache hit, exit the workflow
      - name: Exit workflow if cache hit
        if: steps.wolfprov-cache.outputs.cache-hit == 'true'
        run: |
          echo "Found cached build, exiting build job"
          exit 0

      - name: Checkout wolfProvider
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Convert OpenSSL branch name to commit hash if needed
      - name: Get OpenSSL commit hash
        id: openssl-ref
        run: |
          if [[ "${{ inputs.openssl_ref }}" =~ ^[0-9a-f]{40}$ ]]; then
            echo "ref=${{ inputs.openssl_ref }}" >> $GITHUB_OUTPUT
          else
            sha=$(curl -s "https://api.github.com/repos/openssl/openssl/commits/${{ inputs.openssl_ref }}" | jq -r '.sha')
            echo "ref=$sha" >> $GITHUB_OUTPUT
            echo "OpenSSL ref ${{ inputs.openssl_ref }} is commit $sha"
          fi

      # Look for a cached version of OpenSSL
      - name: Checking OpenSSL in cache
        uses: actions/cache@v4
        id: openssl-cache
        with:
          path: |
            openssl-install

          key: ossl-depends-${{ steps.openssl-ref.outputs.ref }}
          lookup-only: false

      # Convert WolfSSL branch name to commit hash if needed
      - name: Get WolfSSL commit hash
        id: wolfssl-ref
        run: |
          if [[ "${{ inputs.wolfssl_ref }}" =~ ^[0-9a-f]{40}$ ]]; then
            echo "ref=${{ inputs.wolfssl_ref }}" >> $GITHUB_OUTPUT
          else
            sha=$(curl -s "https://api.github.com/repos/wolfssl/wolfssl/commits/${{ inputs.wolfssl_ref }}" | jq -r '.sha')
            echo "ref=$sha" >> $GITHUB_OUTPUT
            echo "WolfSSL ref ${{ inputs.wolfssl_ref }} is commit $sha"
          fi

      # Look for a cached version of WolfSSL
      - name: Checking WolfSSL in cache
        uses: actions/cache@v4
        id: wolfssl-cache
        with:
          path: |
            wolfssl-install

          key: wolfssl-depends-${{ steps.wolfssl-ref.outputs.ref }}
          lookup-only: false

      - name: Build wolfProvider
        run: |
          OPENSSL_TAG=${{ inputs.openssl_ref }} WOLFSSL_TAG=${{ inputs.wolfssl_ref }} ./scripts/build-wolfprovider.sh

      - name: Print errors
        if: ${{ failure() }}
        run: |
          if [ -f test-suite.log ] ; then
            cat test-suite.log
          fi
