name: Build wolfProvider

on:
  workflow_call:
    inputs:
      wolfssl_ref:
        required: true
        type: string
      openssl_ref:
        required: true
        type: string
      replace_default:
        required: false
        type: boolean
        default: false

jobs:
  build_wolfprovider_common:
    name: Build wolfProvider
    runs-on: ubuntu-22.04
    # Run inside Debian Bookworm to match packaging environment
    container:
      image: debian:bookworm
      env:
        DEBIAN_FRONTEND: noninteractive
    timeout-minutes: 20
    env:
      WOLFSSL_PACKAGES_PATH: /tmp/wolfssl-packages
      OPENSSL_PACKAGES_PATH: /tmp/openssl-packages
      WOLFPROV_PACKAGES_PATH: /tmp/wolfprov-packages
    steps:
      # Install git prior to cloning to ensure we have the full repo
      # TODO: create a docker with these pre-installed
      - name: Install common dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
            build-essential \
            devscripts \
            debhelper \
            dh-autoreconf \
            libtool \
            pkg-config \
            git \
            wget \
            curl \
            ca-certificates \
            openssl \
            dpkg-dev \
            lintian \
            fakeroot \
            dh-exec \
            equivs \
            expect \
            xxd \
            bc \
            libdistro-info-perl

      - name: Checkout wolfProvider
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: true

      # Avoid "detected dubious ownership" warning
      - name: Ensure the working directory safe
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      # When running on a fork the upstream tags are not present, so fetch them explicitly
      - name: Fetch tags from upstream(for Debian versioning)
        run: |
          git remote add upstream https://github.com/wolfSSL/wolfProvider.git || true
          git fetch upstream --tags --no-recurse-submodules

      # Cache wolfSSL packages
      - name: Cache wolfSSL packages
        id: cache-wolfssl
        uses: actions/cache@v4
        with:
          path: ${{ env.WOLFSSL_PACKAGES_PATH }}
          key: |
            wolfssl-${{ runner.os }}-${{ matrix.arch || 'noarch' }}-${{ inputs.wolfssl_ref }}-${{ hashFiles('debian/install-wolfssl.sh') }}
          save-always: true
      
      - name: Install wolfSSL from cache
        if: steps.cache-wolfssl.outputs.cache-hit == 'true'
        run: |
          apt install --reinstall -y --allow-downgrades --allow-change-held-packages ${{ env.WOLFSSL_PACKAGES_PATH }}/*.deb

      # Only install wolfSSL if cache not found
      - name: Install wolfSSL
        if: steps.cache-wolfssl.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss for wolfSSL — installing..."
          $GITHUB_WORKSPACE/debian/install-wolfssl.sh --tag ${{ inputs.wolfssl_ref }} ${{ env.WOLFSSL_PACKAGES_PATH }}

      # Cache OpenSSL packages
      - name: Cache OpenSSL packages
        id: cache-openssl
        uses: actions/cache@v4
        with:
          path: ${{ env.OPENSSL_PACKAGES_PATH }}
          key: |
            openssl-${{ runner.os }}-${{ matrix.arch || 'noarch' }}-replaceDefault=${{ inputs.replace_default }}-wolfsslRef=${{ inputs.wolfssl_ref }}-${{ hashFiles('debian/install-openssl.sh') }}
          save-always: true

      - name: Install OpenSSL from cache
        if: steps.cache-openssl.outputs.cache-hit == 'true'
        run: |
          apt install --reinstall -y --allow-downgrades --allow-change-held-packages ${{ env.OPENSSL_PACKAGES_PATH }}/*.deb

      # Only install OpenSSL if cache not found
      - name: Install OpenSSL
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss for OpenSSL — installing..."
          $GITHUB_WORKSPACE/debian/install-openssl.sh ${{ inputs.replace_default && '--replace-default' || '' }} ${{ env.OPENSSL_PACKAGES_PATH }}

      - name: Install wolfProvider
        run: |
          $GITHUB_WORKSPACE/debian/install-wolfprov.sh ${{ env.WOLFPROV_PACKAGES_PATH }}

      - name: List packages directories
        run: |
          ls -la ${{ env.WOLFPROV_PACKAGES_PATH }}
          ls -la ${{ env.WOLFSSL_PACKAGES_PATH }}
          ls -la ${{ env.OPENSSL_PACKAGES_PATH }}

      - name: Save all packages to cache for use by other workflows
        uses: actions/cache/save@v4
        continue-on-error: true
        with:
          path: |
            ${{ env.WOLFSSL_PACKAGES_PATH }}
            ${{ env.OPENSSL_PACKAGES_PATH }}
            ${{ env.WOLFPROV_PACKAGES_PATH }}
          key: openssl-wolfprov-debian-packages-${{ github.sha }}${{ inputs.replace_default && '-replace-default' || '' }}

      # Save all packages in a single artifact for consumers
      # TODO: support debug builds
      - name: Upload wolfProvider artifacts
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: openssl-wolfprov-debian-packages-${{ github.sha }}${{ inputs.replace_default && '-replace-default' || '' }}
          path: |
            ${{ env.WOLFSSL_PACKAGES_PATH }}/*.deb
            ${{ env.WOLFSSL_PACKAGES_PATH }}/*.dsc
            ${{ env.WOLFSSL_PACKAGES_PATH }}/*.tar.gz
            ${{ env.OPENSSL_PACKAGES_PATH }}/*.deb
            ${{ env.OPENSSL_PACKAGES_PATH }}/*.dsc
            ${{ env.OPENSSL_PACKAGES_PATH }}/*.tar.gz
            ${{ env.WOLFPROV_PACKAGES_PATH }}/*.deb
            ${{ env.WOLFPROV_PACKAGES_PATH }}/*.dsc
            ${{ env.WOLFPROV_PACKAGES_PATH }}/*.tar.gz
          retention-days: 1
