name: Command Line Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ '*' ] #'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  cmdtest_test:
    name: Command line test
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    strategy:
      matrix:
        openssl_ref: [ 'master', 'openssl-3.5.0' ]
        wolfssl_ref: [ 'v5.8.2-stable' ]
        force_fail: ['WOLFPROV_FORCE_FAIL=1', '']
        debug: ['WOLFPROV_DEBUG=1', '']
    steps:
      - name: Checkout wolfProvider
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build wolfProvider
        run: |
          ${{ matrix.debug }} OPENSSL_TAG=${{ matrix.openssl_ref }} WOLFSSL_TAG=${{ matrix.wolfssl_ref }} ./scripts/build-wolfprovider.sh

      - name: Run tests
        run: |
          ${{ matrix.force_fail }} ${{ matrix.debug }} ./scripts/cmd_test/do-cmd-tests.sh
