name: Codespell test

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout wolfProvider
        uses: actions/checkout@v4

      - name: Create exclude file if needed
        run: |
          if [ ! -f .codespellexcludelines ]; then
            touch .codespellexcludelines
          fi

      - name: Run codespell
        uses: codespell-project/actions-codespell@v2.1
        with:
          check_filenames: true
          check_hidden: true
          # Add comma separated list of words that occur multiple times that should be ignored (sorted alphabetically, case sensitive)
          ignore_words_list: adin,addIn,aNULL,brunch,carryIn,chainG,ciph,cLen,cliKs,dout,emac,haveA,inCreated,inOut,inout,larg,LEAPYEAR,Merget,optionA,parm,parms,repid,rIn,userA,ser,siz,te,Te,toLen
          # The exclude_file contains lines of code that should be ignored. This is useful for individual lines which have non-words that can safely be ignored.
          exclude_file: '.codespellexcludelines'
          # To skip files entirely from being processed, add it to the following list:
          skip: '*.cproject,*.der,*.mtpj,*.pem,*.vcxproj,.git,*.launch,*.scfg,*.revoked,*.txt'

      - name: Print errors
        if: ${{ failure() }}
        run: |
          if [ -f test-suite.log ] ; then
            cat test-suite.log
          fi
