name: Debian Package Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  bookworm:
    runs-on: ubuntu-22.04
    # Important: use Debian Bookworm for compatibility
    container:
      image: debian:bookworm   # or debian:bookworm-slim
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
    - name: Set up environment
      run: |
        # Update package lists
        apt-get update
        # Install build dependencies
        apt-get install -y \
          build-essential \
          devscripts \
          debhelper \
          dh-autoreconf \
          libtool \
          pkg-config \
          git \
          wget \
          curl \
          ca-certificates \
          openssl \
          dpkg-dev \
          lintian \
          fakeroot \
          equivs
        # Install additional tools for testing
        apt-get install -y \
          expect \
          xxd

    # Avoid "detected dubious ownership" warning
    - name: Ensure the working directory safe
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Checkout wolfProvider
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - run: |
        # Fetch tags
        git fetch --tags
        # List all tags
        git tag -l

    - name: Install wolfssl debian package
      run: |
        mkdir -p "/tmp/wolfssl-pkg"
        cd "/tmp/wolfssl-pkg"
        
        # Install wolfssl packages
        chmod +x $GITHUB_WORKSPACE/debian/install-wolfssl.sh
        $GITHUB_WORKSPACE/debian/install-wolfssl.sh \
          $GITHUB_WORKSPACE/.github/packages/debian-wolfssl.tar.gz \
          "/tmp/wolfssl-pkg"

        # Create wolfprov-packages directory and move wolfssl files there
        mkdir -p "/tmp/wolfprov-packages"
        echo "Moving wolfssl files to artifacts directory..."
        
        # Copy all wolfssl-related files (source and binary packages)
        find /tmp/wolfssl-pkg -name "*wolfssl*" -type f -name "*.deb" -exec cp {} /tmp/wolfprov-packages/ \;
        find /tmp/wolfssl-pkg -name "*wolfssl*" -type f -name "*.dsc" -exec cp {} /tmp/wolfprov-packages/ \;
        find /tmp/wolfssl-pkg -name "*wolfssl*" -type f -name "*.tar.gz" -exec cp {} /tmp/wolfprov-packages/ \;
        find /tmp/wolfssl-pkg -name "*wolfssl*" -type f -name "*.orig.tar.gz" -exec cp {} /tmp/wolfprov-packages/ \;
        
        echo "WolfSSL files in artifacts directory:"
        ls -la /tmp/wolfprov-packages/*wolfssl* || true

    - name: Build Debian package
      run: |
        # Bypass the warning prompt with 'yes Y' 
        yes Y | ./scripts/build-wolfprovider.sh --debian $FIPS_FLAG

        # List generated packages
        echo "Generated Packages:"
        ls -la ../*.deb ../*.dsc ../*.tar.gz || true

    - name: Install package
      run: |
        # Find the package file
        PACKAGE_FILE=$(find ../ -name "libwolfprov_*.deb" | head -n1)
        if [ -z "$PACKAGE_FILE" ]; then
          echo "No package file found!"
          ls -la ../
          exit 1
        fi

        echo "Installing package: $PACKAGE_FILE and dependencies"
        apt install -y ./"$PACKAGE_FILE"

        # Verify installation
        echo "Package Installation Verification:"
        dpkg -l | grep libwolfprov
        dpkg -L libwolfprov

    - name: Test OpenSSL provider functionality
      run: |
        PROVIDER_CONF="/usr/lib/ssl/openssl.cnf.d/wolfprovider.conf"
        PROVIDER_CONF_BACKUP="/tmp/wolfprovider.conf.backup"

        # Temporarily move wolfprovider config so we can toggle between providers
        echo "3. Temporarily disabling wolfprovider for default provider tests:"
        mkdir -p /tmp/openssl-test
        if [ -f $PROVIDER_CONF ]; then
          mv $PROVIDER_CONF $PROVIDER_CONF_BACKUP
          echo "   - Moved $PROVIDER_CONF to $PROVIDER_CONF_BACKUP"
        else
          echo "$PROVIDER_CONF not found!"
          exit 1
        fi

        # Run the do-cmd-test.sh script to execute interoperability tests
        echo "Running OpenSSL provider interoperability tests..."
        OPENSSL_BIN=$(eval which openssl) ./scripts/cmd_test/do-cmd-tests.sh

        # Restore wolfprovider configuration
        echo "5. Restoring wolfprovider configuration:"
        if [ -f $PROVIDER_CONF_BACKUP ]; then
          mv $PROVIDER_CONF_BACKUP $PROVIDER_CONF
          echo "   - Restored $PROVIDER_CONF from $PROVIDER_CONF_BACKUP"
        fi

        echo "PASS: All provider interoperability tests successful"

    - name: Uninstall package and verify cleanup
      run: |
        # Uninstall the package
        apt-get remove --purge -y libwolfprov

        # Verify the package is removed
        if dpkg -l | grep -q libwolfprov; then
          echo "Package still installed after removal"
          dpkg -l | grep libwolfprov
          exit 1
        else
          echo "Package successfully removed"
        fi

        # Check if the config file is removed
        if [ -f /usr/lib/ssl/openssl.cnf.d/wolfprovider.conf ]; then
          echo "wolfprovider.conf still exists after package removal"
          ls -la /usr/lib/ssl/openssl.cnf.d/
          exit 1
        else
          echo "wolfprovider.conf successfully removed"
        fi

        # Check if the library files are removed
        if [ -f /usr/lib/*/ossl-modules/libwolfprov.so ]; then
          echo "libwolfprov.so still exists after package removal"
          find /usr/lib -name "libwolfprov.so*" 2>/dev/null || true
          exit 1
        else
          echo "libwolfprov.so successfully removed"
        fi

        # Verify default OpenSSL provider is active
        echo "Verifying Default Provider is Active:"
        openssl list -providers

        # Verify that the default provider is present and active
        echo "Checking default provider status:"
        if openssl list -providers | grep -q "default" && \
           openssl list -providers | grep -q "OpenSSL Default Provider" && \
           openssl list -providers | grep -q "status: active"; then
          echo "Default provider is present and active"
        else
          echo "Default provider verification failed"
          echo "Provider output:"
          openssl list -providers
          exit 1
        fi

        echo "Package uninstallation and cleanup verification successful"

    - name: Move package artifacts
      run: |
        # Create a clean artifacts directory
        mkdir -p "/tmp/wolfprov-packages"
        # Move the generated packages to the artifacts directory
        mv ../*.deb /tmp/wolfprov-packages/ || true
        mv ../*.dsc /tmp/wolfprov-packages/ || true
        mv ../*.tar.gz /tmp/wolfprov-packages/ || true

    # Save the build outputs which for use in release packages
    - name: Upload package artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: wolfprovider-debian-packages
        path: |
          /tmp/wolfprov-packages/*.deb
          /tmp/wolfprov-packages/*.dsc
          /tmp/wolfprov-packages/*.tar.gz
        retention-days: 7
