name: IPMItool Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  build_wolfprovider:
    uses: ./.github/workflows/build-wolfprovider.yml
    with:
      wolfssl_ref: ${{ matrix.wolfssl_ref }}
      openssl_ref: ${{ matrix.openssl_ref }}
      fips_ref: ${{ matrix.fips_ref }}
      replace_default: ${{ matrix.replace_default }}
    strategy:
      matrix:
        wolfssl_ref: [ 'v5.8.2-stable' ]
        openssl_ref: [ 'openssl-3.5.2' ]
        fips_ref: [ 'FIPS', 'non-FIPS' ]
        replace_default: [ true ]

  test_ipmitool:
    runs-on: ubuntu-22.04
    needs: build_wolfprovider
    container:
      image: debian:bookworm
      env:
        DEBIAN_FRONTEND: noninteractive
    # This should be a safe limit for the tests to run.
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        ipmitool_ref: [ 'IPMITOOL_1_8_19' ]
        wolfssl_ref: [ 'v5.8.2-stable' ]
        openssl_ref: [ 'openssl-3.5.2' ]
        fips_ref: [ 'FIPS', 'non-FIPS' ]
        force_fail: [ 'WOLFPROV_FORCE_FAIL=1', '' ]
        replace_default: [ true ]
    env:
      WOLFSSL_PACKAGES_PATH: /tmp/wolfssl-packages
      OPENSSL_PACKAGES_PATH: /tmp/openssl-packages
      WOLFPROV_PACKAGES_PATH: /tmp/wolfprov-packages
    steps:
      - name: Checkout wolfProvider
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download packages from build job
        uses: actions/download-artifact@v4
        with:
          name: debian-packages-${{ matrix.fips_ref }}${{ matrix.replace_default && '-replace-default' || '' }}-${{ matrix.wolfssl_ref }}-${{ matrix.openssl_ref }}
          path: /tmp/packages

      - name: Setup package directories
        run: |
          mv /tmp/packages/wolfssl-packages ${{ env.WOLFSSL_PACKAGES_PATH }}
          mv /tmp/packages/openssl-packages ${{ env.OPENSSL_PACKAGES_PATH }}
          mv /tmp/packages/wolfprov-packages ${{ env.WOLFPROV_PACKAGES_PATH }}

      - name: Install wolfSSL/OpenSSL/wolfprov packages
        run: |
          printf "Installing OpenSSL/wolfProvider packages (${{ matrix.fips_ref }}):\n"
          ls -la ${{ env.WOLFSSL_PACKAGES_PATH }}
          ls -la ${{ env.OPENSSL_PACKAGES_PATH }}
          ls -la ${{ env.WOLFPROV_PACKAGES_PATH }}

          apt install --reinstall -y --allow-downgrades --allow-change-held-packages \
            ${{ env.WOLFSSL_PACKAGES_PATH }}/libwolfssl_*.deb

          apt install --reinstall -y --allow-downgrades --allow-change-held-packages \
            ${{ env.OPENSSL_PACKAGES_PATH }}/openssl_*.deb \
            ${{ env.OPENSSL_PACKAGES_PATH }}/libssl3_*.deb \
            ${{ env.OPENSSL_PACKAGES_PATH }}/libssl-dev_*.deb

          apt install --reinstall -y --allow-downgrades --allow-change-held-packages \
            ${{ env.WOLFPROV_PACKAGES_PATH }}/libwolfprov_*.deb

      - name: Verify wolfProvider is properly installed
        run: |
          $GITHUB_WORKSPACE/scripts/verify-install.sh \
            ${{ matrix.replace_default && '--replace-default' || '' }} \
            ${{ matrix.fips_ref == 'FIPS' && '--fips' || '' }}

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y libreadline-dev build-essential autoconf \
            automake libtool pkg-config autoconf-archive wget

      - name: Build ipmitool with wolfProvider
        uses: wolfSSL/actions-build-autotools-project@v1
        with:
          repository: ipmitool/ipmitool
          ref: ${{ matrix.ipmitool_ref }}
          path: ipmitool
          check: false

      - name: Test ipmitool crypto functionality
        working-directory: ipmitool
        shell: bash
        run: |
          set +o pipefail # allow force_fail to work

          # Run version check
          ./src/ipmitool -V

          export ${{ matrix.force_fail }}

          # Test crypto operations by attempting IPMI-over-LAN connection
          # This will use HMAC-SHA1 and other crypto functions even if connection fails
          echo "Testing ipmitool crypto operations via LAN connection attempt..."
          
          # Attempt to connect to a dummy IP - this will trigger crypto initialization
          # The connection will fail, but crypto operations will be attempted
          ./src/ipmitool -I lan -H 127.0.0.1 -U admin -P admin chassis status 2>&1 | tee ipmitool-test.log
          TEST_RESULT=${PIPESTATUS[0]}

          # With WPFF enabled, crypto operations should fail
          # Without WPFF, connection will fail but for different reasons (no IPMI hardware)
          if [ -n "${{ matrix.force_fail }}" ]; then
            # With force_fail, we expect failure due to crypto
            if [ $TEST_RESULT -ne 0 ]; then
              echo "Expected failure with WPFF (crypto operations failed as expected)"
              TEST_RESULT=0  # Mark as success since failure was expected
            else
              echo "ERROR: Command succeeded when it should have failed with WPFF"
              TEST_RESULT=1
            fi
          else
            # Without force_fail, command may fail due to no IPMI hardware, but crypto should work
            # Check that we at least attempted crypto operations
            if grep -q "Error" ipmitool-test.log; then
              echo "Command failed (expected without IPMI hardware), but crypto was attempted"
              TEST_RESULT=0  # Success - crypto worked, just no IPMI hardware
            fi
          fi

          $GITHUB_WORKSPACE/.github/scripts/check-workflow-result.sh $TEST_RESULT ${{ matrix.force_fail }} ipmitool
