name: Simple Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  #pull_request:
    #branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  build_wolfprovider:
    uses: ./.github/workflows/build-wolfprovider.yml
    with:
      wolfssl_ref: ${{ matrix.wolfssl_ref }}
      openssl_ref: ${{ matrix.openssl_ref }}
    strategy:
      matrix:
        wolfssl_ref: [ 
          'master', 
          'v5.8.2-stable',
          'v5.8.0-stable']
        # Test against the newest of each minor version
        openssl_ref: [
          'openssl-3.5.2',
          'openssl-3.4.2',
          'openssl-3.3.4',
          'openssl-3.2.5',
          'openssl-3.1.8',
          'openssl-3.0.17']
        force_fail: ['WOLFPROV_FORCE_FAIL=1', '']
        debug: ['WOLFPROV_DEBUG=1', '']

  simple_test:
    name: Simple Test
    runs-on: ubuntu-22.04
    needs: build_wolfprovider
    timeout-minutes: 20
    strategy:
      matrix:
        wolfssl_ref: [ 
          'master', 
          'v5.8.2-stable', 
          'v5.8.0-stable']
        # Test against the newest of each minor version
        openssl_ref: [
          'openssl-3.5.2',
          'openssl-3.4.2',
          'openssl-3.3.4',
          'openssl-3.2.5',
          'openssl-3.1.8',
          'openssl-3.0.17']
        force_fail: ['WOLFPROV_FORCE_FAIL=1', '']
        debug: ['WOLFPROV_DEBUG=1', '']
    steps:
      - name: Checkout wolfProvider
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Retrieving wolfProvider from cache
        # Debug builds are not currently supported by build-wolfprovider.yml
        # so those are manually built as a separate step.
        if: ${{ matrix.debug == '' }}
        uses: actions/cache/restore@v4
        id: wolfprov-cache-restore
        with:
          path: |
            wolfssl-install
            wolfprov-install
            openssl-install/lib64
            openssl-install/include
            openssl-install/bin

          key: wolfprov-${{ matrix.wolfssl_ref }}-${{ matrix.openssl_ref }}-${{ github.sha }}
          # Normally we would fail on cache miss, but we rebuild below 
          # for the DEBUG build.
          fail-on-cache-miss: false

      - name: Build and test wolfProvider
        # Only run the test for a cache miss. On hit, we've already run the test.
        if: steps.wolfprov-cache-restore.cache-hit != 'true'
        run: |
          ${{ matrix.debug }} \
            OPENSSL_TAG=${{ matrix.openssl_ref }} \
            WOLFSSL_TAG=${{ matrix.wolfssl_ref }} \
            ./scripts/build-wolfprovider.sh

      - name: Print errors
        if: ${{ failure() }}
        run: |
          if [ -f test-suite.log ] ; then
            cat test-suite.log
          fi
